-- Schema base (execute dentro do banco escolhido)
-- Ex.: USE seu_banco; SOURCE schema.sql;

CREATE TABLE IF NOT EXISTS jornadas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  COD_UO INT NOT NULL DEFAULT 0,
  SUPERVISOR_EQUIPE VARCHAR(255) NULL,
  LIDER_CONTROLADOR VARCHAR(255) NULL,
  NOME_CONTROLADOR VARCHAR(255) NULL,
  NOME_EQUIPE VARCHAR(255) NOT NULL,
  COD_CLASSIFICACAO_DINAMICO VARCHAR(50) NULL,
  META VARCHAR(50) NULL,
  US_EXEC VARCHAR(50) NULL,
  EXECUTADOS VARCHAR(50) NULL,
  PRODUTIVOS VARCHAR(50) NULL,
  IMPRODUTIVOS VARCHAR(50) NULL,

  INICIO_JORNADA DATETIME NULL,
  PRIMEIRO_ATENDIMENTO DATETIME NULL,
  INICIO_REFEICAO DATETIME NULL,
  TERMINO_REFEICAO DATETIME NULL,
  ULTIMO_ATENDIMENTO DATETIME NULL,
  FIM_JORNADA DATETIME NULL,

  HORA VARCHAR(10) NOT NULL DEFAULT '',
  DATA_DIA DATE NOT NULL,

  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  KEY idx_data_dia (DATA_DIA),
  KEY idx_nome_equipe (NOME_EQUIPE),
  UNIQUE KEY uq_jornada_slot (DATA_DIA, COD_UO, NOME_EQUIPE, HORA)
);

ALTER TABLE jornadas
  ADD COLUMN IF NOT EXISTS META VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS US_EXEC VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS EXECUTADOS VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS PRODUTIVOS VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS IMPRODUTIVOS VARCHAR(50) NULL;
